# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 808)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(888, 808))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.129353 rgba(75, 69, 224, 255), stop:0.502488 rgba(141, 85, 255, 255), stop:0.875622 rgba(130, 0, 255, 255));\n"
"font-family: Noto Sans SC;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.balance_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.balance_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255. 255. 40);\n"
"border-radius: 7px")
        self.balance_frame.setObjectName("balance_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.balance_frame)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_balance = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_balance.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_balance.setObjectName("label_balance")
        self.verticalLayout.addWidget(self.label_balance)
        self.label_summa = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_summa.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 30pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_summa.setObjectName("label_summa")
        self.verticalLayout.addWidget(self.label_summa)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_3.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_3.setStyleSheet("\n"
"background-color: none;\n"
"border: none;\n"
"padding-top: 10px")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/north_east_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_dohod = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_dohod.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bond;\n"
"padding-top: 10px")
        self.label_dohod.setObjectName("label_dohod")
        self.horizontalLayout.addWidget(self.label_dohod)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_summa_dohod = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_summa_dohod.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_summa_dohod.setObjectName("label_summa_dohod")
        self.verticalLayout.addWidget(self.label_summa_dohod)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_5.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_5.setStyleSheet("\n"
"background-color: none;\n"
"border: none;\n"
"padding-top: 10px")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Downloads/south_east_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_rashod = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_rashod.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bond;\n"
"padding-top: 10px")
        self.label_rashod.setObjectName("label_rashod")
        self.horizontalLayout_2.addWidget(self.label_rashod)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_summa_rashod = QtWidgets.QLabel(parent=self.balance_frame)
        self.label_summa_rashod.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_summa_rashod.setObjectName("label_summa_rashod")
        self.verticalLayout.addWidget(self.label_summa_rashod)
        self.horizontalLayout_7.addWidget(self.balance_frame)
        self.categories_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.categories_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255. 255. 40);\n"
"border-radius: 7px")
        self.categories_frame.setObjectName("categories_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.categories_frame)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_category = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_category.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_category.setObjectName("label_category")
        self.verticalLayout_2.addWidget(self.label_category)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_10.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_10.setStyleSheet("background-color: none;\n"
"border: none")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../../Downloads/shopping_cart_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.label_shop = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_shop.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none")
        self.label_shop.setObjectName("label_shop")
        self.horizontalLayout_6.addWidget(self.label_shop)
        self.label_balance_shop = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_balance_shop.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_balance_shop.setObjectName("label_balance_shop")
        self.horizontalLayout_6.addWidget(self.label_balance_shop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_15.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_15.setStyleSheet("background-color: none;\n"
"border: none")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../Downloads/stadia_controller_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.label_enterteiment = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_enterteiment.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none")
        self.label_enterteiment.setObjectName("label_enterteiment")
        self.horizontalLayout_5.addWidget(self.label_enterteiment)
        self.label_balance_enterteiment = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_balance_enterteiment.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_balance_enterteiment.setObjectName("label_balance_enterteiment")
        self.horizontalLayout_5.addWidget(self.label_balance_enterteiment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_16 = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_16.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_16.setStyleSheet("background-color: none;\n"
"border: none")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../../Downloads/apparel_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_clothes = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_clothes.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none")
        self.label_clothes.setObjectName("label_clothes")
        self.horizontalLayout_4.addWidget(self.label_clothes)
        self.label_balance_clothes = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_balance_clothes.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_balance_clothes.setObjectName("label_balance_clothes")
        self.horizontalLayout_4.addWidget(self.label_balance_clothes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_21 = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_21.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_21.setStyleSheet("background-color: none;\n"
"border: none")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../../Downloads/menu_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.label_other = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_other.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none")
        self.label_other.setObjectName("label_other")
        self.horizontalLayout_3.addWidget(self.label_other)
        self.label_balance_other = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_balance_other.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_balance_other.setObjectName("label_balance_other")
        self.horizontalLayout_3.addWidget(self.label_balance_other)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addWidget(self.categories_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_new_track = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_new_track.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 10pt;\n"
"background-color: none;\n"
"border: 1px solid rgba(250, 250, 250, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/add_circle_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_new_track.setIcon(icon)
        self.pushButton_new_track.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_new_track.setObjectName("pushButton_new_track")
        self.horizontalLayout_8.addWidget(self.pushButton_new_track)
        self.pushButton_delete_track = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete_track.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 10pt;\n"
"background-color: none;\n"
"border: 1px solid rgba(250, 250, 250, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/delete_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_delete_track.setIcon(icon1)
        self.pushButton_delete_track.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_delete_track.setObjectName("pushButton_delete_track")
        self.horizontalLayout_8.addWidget(self.pushButton_delete_track)
        self.pushButton_izmenit_track = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_izmenit_track.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 10pt;\n"
"background-color: none;\n"
"border: 1px solid rgba(250, 250, 250, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/edit_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_izmenit_track.setIcon(icon2)
        self.pushButton_izmenit_track.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_izmenit_track.setObjectName("pushButton_izmenit_track")
        self.horizontalLayout_8.addWidget(self.pushButton_izmenit_track)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setStyleSheet(u"QTableView {\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-bottom-right-radius: 7px; \n"
"border-bottom-left-radius: 7px; \n"
"color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(53, 53, 53);\n"
"color: white;\n"
"border: none;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgba(255,255,255,50);\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"	border: none;\n"
"	color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"")
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_3.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Трекер расходов"))
        self.label_balance.setText(_translate("MainWindow", "Текущий баланс:"))
        self.label_summa.setText(_translate("MainWindow", "1000 руб"))
        self.label_dohod.setText(_translate("MainWindow", " Доход"))
        self.label_summa_dohod.setText(_translate("MainWindow", "1000 руб"))
        self.label_rashod.setText(_translate("MainWindow", "Расход"))
        self.label_summa_rashod.setText(_translate("MainWindow", "1000 руб"))
        self.label_category.setText(_translate("MainWindow", "Категории расходов"))
        self.label_shop.setText(_translate("MainWindow", "Покупки"))
        self.label_balance_shop.setText(_translate("MainWindow", "1000 руб"))
        self.label_enterteiment.setText(_translate("MainWindow", "Развлечения"))
        self.label_balance_enterteiment.setText(_translate("MainWindow", "1000 руб"))
        self.label_clothes.setText(_translate("MainWindow", "Одежда"))
        self.label_balance_clothes.setText(_translate("MainWindow", "1000 руб"))
        self.label_other.setText(_translate("MainWindow", "Другое"))
        self.label_balance_other.setText(_translate("MainWindow", "1000 руб"))
        self.pushButton_new_track.setText(_translate("MainWindow", "Новая транкзация"))
        self.pushButton_delete_track.setText(_translate("MainWindow", "Удалить транзакцию"))
        self.pushButton_izmenit_track.setText(_translate("MainWindow", "Изменить транзакцию"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
