# Form implementation generated from reading ui file 'new_track.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_New_track(object):
    def setupUi(self, New_track):
        New_track.setObjectName("New_track")
        New_track.resize(481, 415)
        New_track.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.129353 rgba(75, 69, 224, 255), stop:0.502488 rgba(141, 85, 255, 255), stop:0.875622 rgba(130, 0, 255, 255));\n"
"font-family: Noto Sans SC;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(New_track)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=New_track)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255. 255. 40);\n"
"border-radius: 7px")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_new_track = QtWidgets.QLabel(parent=self.frame)
        self.label_new_track.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.label_new_track.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_new_track.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_new_track.setObjectName("label_new_track")
        self.verticalLayout.addWidget(self.label_new_track)
        self.comboBox_category = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_category.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white; \n"
"}\n"
"\n"
"QComboBox::item {\n"
"color: white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
" color: white; \n"
" background-color: black; \n"
"}")
        self.comboBox_category.setObjectName("comboBox_category")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.comboBox_category.addItem("")
        self.verticalLayout.addWidget(self.comboBox_category)
        self.data = QtWidgets.QDateEdit(parent=self.frame)
        self.data.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px")
        self.data.setDate(QtCore.QDate(2024, 1, 1))
        self.data.setObjectName("data")
        self.verticalLayout.addWidget(self.data)
        self.lineEdit_opisanie = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_opisanie.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px")
        self.lineEdit_opisanie.setObjectName("lineEdit_opisanie")
        self.verticalLayout.addWidget(self.lineEdit_opisanie)
        self.lineEdit_summa = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_summa.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px")
        self.lineEdit_summa.setObjectName("lineEdit_summa")
        self.verticalLayout.addWidget(self.lineEdit_summa)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_2.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.pushButton_add = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_add.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15pt;\n"
"background-color: none;\n"
"border: 1px solid rgba(250, 250, 250, 40);\n"
"border-radius: 7px;\n"
"width: 230px;\n"
"height: 50px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/add_circle_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24 (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(New_track)
        self.comboBox_category.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(New_track)

    def retranslateUi(self, New_track):
        _translate = QtCore.QCoreApplication.translate
        New_track.setWindowTitle(_translate("New_track", "Dialog"))
        self.label_new_track.setText(_translate("New_track", "Новая транзакция"))
        self.comboBox_category.setCurrentText(_translate("New_track", "Выберите категорию"))
        self.comboBox_category.setItemText(0, _translate("New_track", "Покупки"))
        self.comboBox_category.setItemText(1, _translate("New_track", "Развлечения"))
        self.comboBox_category.setItemText(2, _translate("New_track", "Одежда"))
        self.comboBox_category.setItemText(3, _translate("New_track", "Другое"))
        self.comboBox_category.setItemText(4, _translate("New_track", "Работа"))
        self.lineEdit_opisanie.setPlaceholderText(_translate("New_track", "Подробности"))
        self.lineEdit_summa.setPlaceholderText(_translate("New_track", "Сумма "))
        self.comboBox_2.setItemText(0, _translate("New_track", "Расход"))
        self.comboBox_2.setItemText(1, _translate("New_track", "Доход"))
        self.pushButton_add.setText(_translate("New_track", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    New_track = QtWidgets.QDialog()
    ui = Ui_New_track()
    ui.setupUi(New_track)
    New_track.show()
    sys.exit(app.exec())
